#! /bin/sh

sxhkd &
nitrogen --restore &

bspc monitor -d "" "" "" "" "" ""

bspc config border_width         4
bspc config window_gap         	20 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config focused_border_color "#a52654"
bspc config normal_border_color "#120a12"


# Workspace 1
bspc rule -a qutebrowser desktop='^1' state=tiling follow=on
bspc rule -a "Firefox Developer Edition" desktop='^1' state=tiling follow=on

# Workspace 2 
bspc rule -a URxvt desktop='^2' state=tiling follow=on

# Workspace 3 
bspc rule -a Nautilus desktop='^3' state=floating follow=on

# Workspace 4 
bspc rule -a Code desktop='^4' state=tiling follow=on

# Workspace 5 
bspc rule -a Virt-manager desktop='^5' state=tiling follow=on

# Workspace 6 
bspc rule -a Deluge desktop='^6' state=tiling follow=on

# Floating
bspc rule -a XTerm state=floating folow=on

$HOME/.config/polybar/launch.sh
